### Laboratory Task 5

**Name:** Karylle B. dela Cruz <br>
**Section:** DS4A

1. Perform Standard Imports

In [1]:
import torch
import numpy as np
import sys

2. Create a function called set_seed() that accepts seed: int as a parameter, this function must return nothing but just set the seed to a certain value.

In [2]:
def set_seed(seed):
    torch.manual_seed(seed)
    np.random.seed(seed)

2. Create a function called set_seed() that accepts seed: int as a parameter, this function must return nothing but just set the seed to a certain value.

In [3]:
set_seed(42)
arr = np.random.randint(0, 5, size=6)
print(arr)
print(arr.dtype)

[3 4 2 4 4 1]
int32


4. Create a tensor "x" from the array above

In [4]:
x = torch.from_numpy(arr)
x

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)

5. Change the dtype of x from int32 to int64

In [5]:
x = x.type(torch.int64)
print(x.dtype)

torch.int64


6. Reshape x into a 3x2 tensor

In [6]:
x = x.reshape(3,2)
x

tensor([[3, 4],
        [2, 4],
        [4, 1]])

7. Return the right-hand column of tensor x

In [7]:
x[:,1]

tensor([4, 4, 1])

8. Without changing x, return a tensor of square values of x

In [8]:
print(x.pow(2))

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


9. Create a tensor y with the same number of elements as x, that can be matrix-multiplied with x

In [9]:
set_seed(42)
y = torch.randint(0, 5, (2,3))
y

tensor([[2, 2, 1],
        [4, 1, 0]])

10. Find the matrix product of x and y.

In [11]:
print(x @ y)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


### End